#!/usr/bin/env python3
"""Generate include/trig_table.h: 256-entry sine table, Q14 (1.0 = 16384).

Angles in the game are 16-bit (65536 = one full turn); the table is indexed
with angle >> 8. cos(a) is sin(a + 64).
"""
import math
import sys

out = sys.argv[1] if len(sys.argv) > 1 else "include/trig_table.h"
vals = [round(math.sin(2 * math.pi * i / 256) * 16384) for i in range(256)]
lines = ["/* Generated by tools/gen_trig.py - do not edit. */",
         "#ifndef TRIG_TABLE_H", "#define TRIG_TABLE_H", "",
         "#include <stdint.h>", "",
         "static const int16_t game_sin_table[256] = {"]
for i in range(0, 256, 8):
    lines.append("    " + ", ".join(str(v) for v in vals[i:i + 8]) + ",")
lines += ["};", "", "#endif", ""]
with open(out, "w", newline="\n") as f:
    f.write("\n".join(lines))
